version: "3.9"

services:
  database:
    image: postgres:14.6
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - database:/var/lib/postgresql/data
    ports:
        - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_HOST: database
    ports:
      - "8000:8000"

volumes:
    database:
